--- 
language: node_js
node_js: 
  - "12"
sudo: required
dist: xenial

install: 
  - "cd ./deliverable-2/frontend"
  - "npm install"
  - "cd ../backend"
  - "npm install"
  - "cd ../.."

jobs: 
  include: 
    - 
      stage: Test
      name: "Lint test"
      script: 
        - "echo \"Running lint tests\""
    - 
      name: "Unit test"
      script: 
        - "cd ./deliverable-2/backend && npm test && cd../.."
    - 
      stage: Deploy
      install: skip
      script: cd ./deliverable-2
      deploy: 
        - 
          api_key: $HEROKU_AUTH_TOKEN
          app: refutalent-dev
          provider: heroku
          on: 
            branch: develop
        - 
          api_key: $HEROKU_AUTH_TOKEN
          app: refutalent
          provider: heroku
          on: 
            branch: main
